[project]
name = "azquotes-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx[http2]>=0.28.1",
    "parsel>=1.10.0",
    "rich>=13.9.4",
]
